#!/usr/bin/env bash

# Set up autograder files
PATH_TO_GRADE_PY='/autograder/grader/autograder/'

# cd to the autograder repo, cloned as `grader/`
#cd ${PATH_TO_GRADE_PY}

python3 source/checkFiles.py

# the autograder produced a correctly formatted results.json, cp to the right place
#cp ${PATH_TO_GRADE_PY}results.json /autograder/results/results.json